#***********************************************************************
# Script           : DeployVM.ps1
# Author           : Richard Hogan
# Created          : 19-08-2021
# ***********************************************************************
# <copyright file="DeployVM.ps1" company="N/A">
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
# KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
# </copyright>
# <summary></summary>
# <auto-generated/>
# ***********************************************************************

Clear-Host

#Declaring Variables
$Path = 'Z:\Development\themicrosoftcloudblog\Samples\BICEP\Deploy Virtual Machines\Deploy Multiple VMs\'
$VNetBicepFile = $Path + 'VNET-Deployment.bicep'
$VMBicepFile = $Path + 'VirtualMachine-Deployment.bicep'

try
{
    Write-Host "Checking Resource Group." -ForegroundColor Yellow
        
    #Set Configuration Variables.
    $VNetName = $Config.Configuration.Deployment.VNetName
    $ResourceGroupName = $Config.Configuration.Deployment.ResourceGroupName
    $Location = $Config.Configuration.Deployment.Region
    $SubNetName = $Config.Configuration.Deployment.SubNetName

    #Check to see if resource group already exists
    $ResourceGroup = Get-AzResourceGroup -name 'VirtualMachines'
    if (!$ResourceGroup)
    {
        #Create Resource Group
        Write-Host "The specified resource Group does not exist, creating resource Group. " -ForegroundColor Yellow
        New-AzResourceGroup -Name 'VirtualMachines' -Location 'uksouth' | Out-Null
        Write-Host "Resource Group Created." -ForegroundColor Green
    }

    Write-Host "DEPLOYING RESOURCES." -ForegroundColor Yellow
    Write-Host "Deploying VNet." -ForegroundColor Yellow

    #Deploying VNet seperately as this will be used for each VM in this sample
    New-AzResourceGroupDeployment -ResourceGroupName  VirtualMachines -TemplateFile `
        $VNetBicepFile -VNetName $VNetName -SubNetName $SubNetName -Location $Location | Out-Null

    Write-Host "VNet Deployed." -ForegroundColor Green
    Write-Host "Deploying Virtual Machines and components." -ForegroundColor Yellow

    #Get VNetID so it can be linked to the VM.
    $VNetID = Get-AzResource -name $VNetName -ResourceGroupName 'VirtualMachines'

    #Deploy rest of components
    foreach ($VM in $Config.Configuration.VirtualMachines.VM)
    {
        New-AzResourceGroupDeployment -ResourceGroupName $ResourceGroupName -TemplateFile `
            $VMBicepFile -VMName $VM.VMName -SubNetName $SubNetName -Location $Location -OSDiskName `
            $VM.OSDiskName -VNetID $VNetID.id -NICName $VM.NetworkInterface -PublicIPAddressName $VM.PublicIPName | Out-Null

        Write-Host "Virtual Machine Deployed." -ForegroundColor Green
        Write-Host
    }

    Write-Host "Successfully Deployed All Resources." -ForegroundColor Green
}
catch
{
    Write-Host "Error: $($_.Exception.Message)" -ForegroundColor Red
}








