
#***********************************************************************
# Script           : DeploySingleVM.ps1
# Author           : Richard Hogan
# Created          : 06-08-2021
# ***********************************************************************
# <copyright file="DeploySingleVM.ps1" company="N/A">
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
# KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
# </copyright>
# <summary></summary>
# <auto-generated/>
# ***********************************************************************

Clear-Host

#Check to see if connection has already been established.
$Context = Get-AzContext
$Path = "Z:\Development\themicrosoftcloudblog\Samples\BICEP\Deploy Virtual Machines\Deploy AD\"
$VNetBicepFile = $Path + 'Active Directory-Deployment.bicep'

$VNetID;
$ResourceGroupName = 'IdentityRG';
$VNetName = 'IdentityVNet';

if(-Not $Context)
{
    #If no context currently exists log on to the tenant.
    try 
    {
        #Connect to Tenant
        Connect-AzAccount
        Write-Host "Succesfully Logged In" -ForegroundColor Green
    }
    catch {
        Write-Host "Something went wrong." -ForegroundColor Red
    }
}

#try {
    Set-AzContext -SubscriptionID '7ac75c45-5ee7-45de-b59c-7877c41e5ce6'
    $VNetID = Get-AzResource -name $VNetName -ResourceGroupName $ResourceGroupName
    New-AzResourceGroupDeployment -ResourceGroupName 'IdentityRG' -TemplateFile ./ActiveDirectory-Deployment.bicep -VMName 'RHAD01' -VNetID $VNetID.Id
#}
#catch {
#    Write-Host "Something went wrong." -ForegroundColor Red
#}
